### ISSUE TITLE
Can add information about how you compiled these

### ISSUE THREAD

**Issue by dannyk96** [ljdursi/coarray-examples#1]
eg gfrotran -fcoarray=lib   or otherwise?

**Comment by ljdursi** [comment]
Excellent point.  I'll add something to the readme.

**Comment by ljdursi** [comment]
Ok, I've got a Makefile and a couple lines in the Readme.  Does that help?

**Comment by dannyk96** [comment]
Thanks.

I see that you have `gfortran 5.1`. 

I had `gfortran 4.9.2` which is the most up to date with the latest `ubuntu 15.04`. This always failed to link as the `_gfortran_caf_num_images` and `_gfortran_caf_sync_images` erroneously get placed in the BSS - I assume by mistake. They should be `U` not `B` otherwise they are multiply defined.

**Comment by dannyk96** [comment]
I have now installed `gfortran 5.1.1` using `wget http://gfortran.com/download/x86_64/gfortran-fetch-and-install.sh`

Using your build instructions, All is now good

```
$ mpirun.mpich -n 2 ./a.out                                           
 Hello, world, from image            1 of            2 !
 Hello, world, from image            2 of            2 !
```

Thanks!

**Comment by ljdursi** [comment]
Great!  Maybe, for as long as gcc-5.1 and opencoarrays aren't widely packaged, it would be useful to include put up a vagrant VM or some other encapsulated environment so people could play with things without having to go through the multistep install package.  I'll give it a try this weekend.
